export const menus = [
    { id: 1, restoId: 'ZWNYv4rcouIqqwKBkazM', name: "Big Mac" },
    { id: 2, restoId: 'ZWNYv4rcouIqqwKBkazM', name: "McChicken" },
    { id: 3, restoId: 'ZWNYv4rcouIqqwKBkazM', name: "Fries" },
    { id: 4, restoId: 'ZWNYv4rcouIqqwKBkazM', name: "Coca Cola" },
    { id: 5, restoId: 'ZWNYv4rcouIqqwKBkazM', name: "Nuggets" },
    { id: 6, restoId: 'ZWNYv4rcouIqqwKBkazM', name: "Frite" },
    { id: 7, restoId: 'TkOQR0LZJqVo6pA9Pl4N', name: "Algérienne" },
    { id: 8, restoId: 'TkOQR0LZJqVo6pA9Pl4N', name: "Barbecue" },
    { id: 9, restoId: 'TkOQR0LZJqVo6pA9Pl4N', name: "Biggy Burger" },
    { id: 10, restoId: 'TkOQR0LZJqVo6pA9Pl4N', name: "Eau Aquafina" },
    { id: 11, restoId: 'TkOQR0LZJqVo6pA9Pl4N', name: "Mirinda Citron" },
    { id: 12, restoId: 'TkOQR0LZJqVo6pA9Pl4N', name: "Mirinda Pomme" },
    { id: 13, restoId: 'Ha2bKyksCxzpKMteCsz6', name: "Super - Deals" },
    { id: 14, restoId: 'Ha2bKyksCxzpKMteCsz6', name: "Nos Salades" },
    { id: 15, restoId: 'Ha2bKyksCxzpKMteCsz6', name: "Nos Tacos" },
    { id: 16, restoId: 'Ha2bKyksCxzpKMteCsz6', name: "Nos Pizzas" },
    { id: 17, restoId: 'Ha2bKyksCxzpKMteCsz6', name: "Nos Burgers" },
    { id: 18, restoId: 'Ha2bKyksCxzpKMteCsz6', name: "Nos Sandwichs" },
    { id: 19, restoId: 'B6jiWaL7IgaCsiAoXpMK', name: "Nouveautés" },
    { id: 20, restoId: 'B6jiWaL7IgaCsiAoXpMK', name: "Promos" },
    { id: 21, restoId: 'B6jiWaL7IgaCsiAoXpMK', name: "Burgers" },
    { id: 22, restoId: 'B6jiWaL7IgaCsiAoXpMK', name: "Menus Enfants" },
    { id: 23, restoId: 'B6jiWaL7IgaCsiAoXpMK', name: "Desserts" },
    { id: 24, restoId: 'B6jiWaL7IgaCsiAoXpMK', name: "Boissons" },
    { id: 25, restoId: 'm2oJn7lE0lMr46kA41gS', name: "Glaces & Desserts" },
    { id: 26, restoId: 'm2oJn7lE0lMr46kA41gS', name: "Boissons" },
    { id: 27, restoId: 'm2oJn7lE0lMr46kA41gS', name: "Pizzas - Pâte Thin" },
    { id: 28, restoId: 'm2oJn7lE0lMr46kA41gS', name: "Pizzas - Pâte Pan" },
    { id: 29, restoId: 'm2oJn7lE0lMr46kA41gS', name: "Pizzas - Pâte Cheezy Crust" },
    { id: 30, restoId: 'm2oJn7lE0lMr46kA41gS', name: "Sandwichs & Calzones" },
    { id: 31, restoId: 'NmCjA4acb3UkZbzPa4kh', name: "Buckets" },
    { id: 32, restoId: 'NmCjA4acb3UkZbzPa4kh', name: "Exclusive Promotions" },
    { id: 33, restoId: 'NmCjA4acb3UkZbzPa4kh', name: "Boxes" },
    { id: 34, restoId: 'NmCjA4acb3UkZbzPa4kh', name: "Menus" },
    { id: 35, restoId: 'NmCjA4acb3UkZbzPa4kh', name: "Sandwich" },
    { id: 36, restoId: 'NmCjA4acb3UkZbzPa4kh', name: "Sides & Drinks" },
    { id: 37, restoId: 'AQvcvZZlXtUImIopXhsC', name: "Boucherie" },
    { id: 38, restoId: 'AQvcvZZlXtUImIopXhsC', name: "Volaille" },
    { id: 39, restoId: 'AQvcvZZlXtUImIopXhsC', name: "Poissonnerie" },
    { id: 40, restoId: 'AQvcvZZlXtUImIopXhsC', name: "Traiteur de la Mer" },
    { id: 41, restoId: 'AQvcvZZlXtUImIopXhsC', name: "Fruits" },
    { id: 42, restoId: 'AQvcvZZlXtUImIopXhsC', name: "Prêt à manger" },
    { id: 43, restoId: 'pnO9LUCNDBp33WGw1sNS', name: "Le monde de bébé" },
    { id: 44, restoId: 'pnO9LUCNDBp33WGw1sNS', name: "Boissons Marjane" },
    { id: 45, restoId: 'pnO9LUCNDBp33WGw1sNS', name: "Légumes, Salades et Herbes" },
    { id: 46, restoId: 'pnO9LUCNDBp33WGw1sNS', name: "Fruits" },
    { id: 47, restoId: 'pnO9LUCNDBp33WGw1sNS', name: "Boucherie" },
    { id: 48, restoId: 'pnO9LUCNDBp33WGw1sNS', name: "Boissons Gazeuses" },
];


export const food_list = [
    { id: 1, name: "Food number 1", price: 13.99 },
    { id: 2, name: "Food number 2", price: 23.99 },
    { id: 3, name: "Food number 3", price: 23.99 },
    { id: 4, name: "Food number 4", price: 33.99 },
]